// Code generated by sqlc. DO NOT EDIT.
// source: account_details.sql

package db

import (
	"context"
)

const createAccountDetails = `-- name: CreateAccountDetails :one
INSERT INTO account_details (
  user_name,
  balance
) VALUES (
  $1, $2
) RETURNING id, user_name, balance, created_at
`

type CreateAccountDetailsParams struct {
	UserName string `json:"user_name"`
	Balance  int64  `json:"balance"`
}

func (q *Queries) CreateAccountDetails(ctx context.Context, arg CreateAccountDetailsParams) (AccountDetail, error) {
	row := q.db.QueryRowContext(ctx, createAccountDetails, arg.UserName, arg.Balance)
	var i AccountDetail
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccountDetails = `-- name: DeleteAccountDetails :exec
DELETE FROM account_details
WHERE id = $1
`

func (q *Queries) DeleteAccountDetails(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccountDetails, id)
	return err
}

const getAccountDetails = `-- name: GetAccountDetails :one
SELECT id, user_name, balance, created_at FROM account_details
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountDetails(ctx context.Context, id int64) (AccountDetail, error) {
	row := q.db.QueryRowContext(ctx, getAccountDetails, id)
	var i AccountDetail
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountDetailsForUpdate = `-- name: GetAccountDetailsForUpdate :one
SELECT id, user_name, balance, created_at FROM account_details
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetAccountDetailsForUpdate(ctx context.Context, id int64) (AccountDetail, error) {
	row := q.db.QueryRowContext(ctx, getAccountDetailsForUpdate, id)
	var i AccountDetail
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE account_details
SET balance = balance + $1
WHERE id = $2
RETURNING id, user_name, balance, created_at
`

type UpdateAccountBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (AccountDetail, error) {
	row := q.db.QueryRowContext(ctx, updateAccountBalance, arg.Amount, arg.ID)
	var i AccountDetail
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountDetails = `-- name: UpdateAccountDetails :one
UPDATE account_details
SET balance = $2
WHERE id = $1
RETURNING id, user_name, balance, created_at
`

type UpdateAccountDetailsParams struct {
	ID      int64 `json:"id"`
	Balance int64 `json:"balance"`
}

func (q *Queries) UpdateAccountDetails(ctx context.Context, arg UpdateAccountDetailsParams) (AccountDetail, error) {
	row := q.db.QueryRowContext(ctx, updateAccountDetails, arg.ID, arg.Balance)
	var i AccountDetail
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}
