// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type AccountDetail struct {
	ID        int64     `json:"id"`
	UserName  string    `json:"user_name"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

type Movie struct {
	ID                int64        `json:"id"`
	Name              string       `json:"name"`
	ProductionCompany string       `json:"production_company"`
	YearReleased      int32        `json:"year_released"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type MovieLike struct {
	ID        sql.NullInt64 `json:"id"`
	MovieID   int64         `json:"movie_id"`
	UserName  string        `json:"user_name"`
	Liked     bool          `json:"liked"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Transaction struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID              int64     `json:"id"`
	SourceAccountID int64     `json:"source_account_id"`
	TargetAccountID int64     `json:"target_account_id"`
	Amount          int64     `json:"amount"`
	CreatedAt       time.Time `json:"created_at"`
}

type User struct {
	UserName          string    `json:"user_name"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
