// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateAccountDetails(ctx context.Context, arg CreateAccountDetailsParams) (AccountDetail, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateMovieLikes(ctx context.Context, arg CreateMovieLikesParams) (MovieLike, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccountDetails(ctx context.Context, id int64) error
	GetAccountDetails(ctx context.Context, id int64) (AccountDetail, error)
	GetAccountDetailsForUpdate(ctx context.Context, id int64) (AccountDetail, error)
	GetMovie(ctx context.Context, id int64) (Movie, error)
	GetMovieForUser(ctx context.Context, arg GetMovieForUserParams) (MovieLike, error)
	GetMoviesByReleasedYear(ctx context.Context, arg GetMoviesByReleasedYearParams) ([]Movie, error)
	GetMoviesFromProductionCompany(ctx context.Context, arg GetMoviesFromProductionCompanyParams) ([]Movie, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]Transaction, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, userName string) (User, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (AccountDetail, error)
	UpdateAccountDetails(ctx context.Context, arg UpdateAccountDetailsParams) (AccountDetail, error)
}

var _ Querier = (*Queries)(nil)
